{
 "title": "rds-simulation",
 "time": { "from": "2025-10-14T12:27:32.000Z", "to": "2025-10-14T15:27:32.000Z" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Anshar map",
   "type": "canvas",
   "gridPos": { "h": 13, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"rds-test-bucket\")\n  |> range(start: -10m)\n  |> filter(fn: (r) => r._measurement == \"rad_dr\" and r._field == \"rad_measurement\" and r.id == \"1\")\n  |> last()\n |> fill(value: 0.0)"
    },
    {
     "query": "from(bucket: \"rds-test-bucket\")\n  |> range(start: -10m)\n  |> filter(fn: (r) => r._measurement == \"rad_dr\" and r._field == \"rad_measurement\" and r.id == \"2\")\n  |> last()\n |> fill(value: 0.0)"
    },
    {
     "query": "from(bucket: \"rds-test-bucket\")\n  |> range(start: -10m)\n  |> filter(fn: (r) => r._measurement == \"rad_dr\" and r._field == \"rad_measurement\" and r.id == \"3\")\n  |> last()\n |> fill(value: 0.0)"
    },
    {
     "query": "from(bucket: \"rds-test-bucket\")\n  |> range(start: -10m)\n  |> filter(fn: (r) => r._measurement == \"rad_dr\" and r._field == \"rad_measurement\" and r.id == \"4\")\n  |> last()\n |> fill(value: 0.0)"
    },
    {
     "query": "from(bucket: \"rds-test-bucket\")\n  |> range(start: -10m)\n  |> filter(fn: (r) => r._measurement == \"rad_dr\" and r._field == \"rad_measurement\" and r.id == \"5\")\n  |> last()\n |> fill(value: 0.0)"
    }
   ]
  },
  {
   "title": "Sensor 1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket:\"rds-test-bucket\") \n  |> range(start: -24h)\n  |> filter(fn: (r) => r._field == \"rad_measurement\")\n  |> filter(fn: (r) => r.id == \"1\")"
    }
   ]
  },
  {
   "title": "Sensor 2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket:\"rds-test-bucket\") \n  |> range(start: -24h)\n  |> filter(fn: (r) => r._field == \"rad_measurement\")\n  |> filter(fn: (r) => r.id == \"2\")"
    }
   ]
  },
  {
   "title": "Sensor 3",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket:\"rds-test-bucket\") \n  |> range(start: -24h)\n  |> filter(fn: (r) => r._field == \"rad_measurement\")\n  |> filter(fn: (r) => r.id == \"3\")"
    }
   ]
  },
  {
   "title": "Sensor 4",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket:\"rds-test-bucket\") \n  |> range(start: -24h)\n  |> filter(fn: (r) => r._field == \"rad_measurement\")\n  |> filter(fn: (r) => r.id == \"4\")"
    }
   ]
  },
  {
   "title": "Sensor 5",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket:\"rds-test-bucket\") \n  |> range(start: -24h)\n  |> filter(fn: (r) => r._field == \"rad_measurement\")\n  |> filter(fn: (r) => r.id == \"5\")"
    }
   ]
  }
 ]
}