apiVersion: 1

datasources:
  - uid: rds-influxdb-ds
    name: InfluxDB
    type: influxdb
    access: proxy
    url: http://rds-influxdb:8086
    isDefault: true
    jsonData:
      version: Flux
      organization: rds-test-org
      defaultBucket: rds-test-bucket
    basicAuth: true
    basicAuthUser: admin
    secureJsonData:
      basicAuthPassword: admin123
      token: rds-test-token